policy:
  approval:
    - or:
      - Kevin made a change
      - Kevin approves

approval_rules:
  - name: Kevin made a change
    if:
      has_author_in:
        users: [ "OGKevin"]
      has_contributor_in:
        users: [ "OGKevin"]
    options:
      allow_author: true
      allow_contributor: true
  - name: Kevin approves
    methods:
      comments:
        - "/lgtm"
      github_review: true
    requires:
      count: 1
      users: [ "OGKevin" ]
